Repository Step3-kakao-tech-campus/Team16_FE, pull requests merged in 2023-10, with the labels that each got.

#58 fix: 폼을 전부 채워도 allFieldsFilled가 false로 나타나는 오류 해결
  src/components/organisms/MRegisterForm.tsx
Labels: Type: Bug

#89 fix: 상세조회 페이지 잘림 현상 해결
  src/pages/detailPet/VDetailPetData.tsx
  src/pages/detailPet/VDetailPetInfo.tsx
Labels: Type: Bug

#90 feat: 현재 위치 설정 안 해도 지도 뜨도록 변경
  src/pages/map/Map.tsx
Labels: Type: Enhancement

#91 feat: 로그인, 회원가입 백엔드 API 연결 수정
  package-lock.json
  package.json
  src/commons/PostCode.tsx
  src/commons/cookie/cookie.ts
  src/commons/cookie/getUser.ts
  src/layouts/VGNB.tsx
  src/layouts/VLargeGNB.tsx
  src/pages/login/LoginInputForm.tsx
  src/pages/signUp/SignupInputForm.tsx
  src/pages/signUp/VSignupInputForm.tsx
Labels: Type: Feature

#95 fix: 특성 점수 부여하는 부분에서 버튼이 클릭되지 않는 문제 해결
  src/pages/register/StatusScore.tsx
  src/pages/register/StatusSelectGroup.tsx
Labels: Type: Fix

#96 feat: 백엔드에서 받은 데이터만 표시하도록 변경
  src/pages/map/Map.tsx
Labels: Type: Feature

#97 fix: api와 통신한대로 안 보이던 것 일부 고침
  src/pages/map/Map.tsx
Labels: Type: Fix

#134 전남대_16조_애니모리_7주차
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/App.tsx
  src/commons/LogoButton.tsx
  src/commons/MonthDays.tsx
  src/commons/SelectBox.tsx
  src/commons/cookie/getUser.ts
  src/layouts/VGNB.tsx
  src/layouts/VLargeGNB.tsx
  src/pages/detailPet/VDetailPetInfo.tsx
  src/pages/home/Home.tsx
  src/pages/home/HomePage.tsx
  src/pages/home/VHome.tsx
  src/pages/login/LoginInputForm.tsx
  src/pages/login/VLoginInputForm.tsx
  src/pages/login/VLoginPage.tsx
  src/pages/map/MapPage.tsx
  src/pages/map/TestMap.tsx
  src/pages/profileList/ProfileCard.tsx
  src/pages/profileList/ProfileListHome.tsx
  src/pages/profileList/ProfileListHomeSkeleton.tsx
  src/pages/profileList/VProfileCard.tsx
  src/pages/profileList/VProfileListHome.tsx
  src/pages/profileList/newList/NewList.tsx
  src/pages/profileList/newList/NewListSkeleton.tsx
  src/pages/profileList/newList/VNewList.tsx
  src/pages/profileList/urgentList/UrgentList.tsx
  src/pages/profileList/urgentList/UrgentListSkeleton.tsx
  src/pages/profileList/urgentList/VUrgentList.tsx
  src/pages/register/Calendar.tsx
  src/pages/register/StatusScore.tsx
  src/pages/register/StatusSelectGroup.tsx
  src/pages/register/VDayModalInput.tsx
  src/pages/register/VMRegisterForm.tsx
  src/pages/register/VRadioGroup.tsx
  src/pages/shelterInfo/ShelterInfo.tsx
  src/pages/shelterInfo/ShelterInfoSkeleton.tsx
  src/pages/shelterInfo/VShelterCard.tsx
  src/pages/shelterInfo/VShelterInfo.tsx
  src/pages/signUp/SignupInputForm.tsx
  src/pages/signUp/VSignupInputForm.tsx
  src/pages/signUp/VSignupPage.tsx
  src/pages/update/UpdateInput.tsx
  src/pages/update/UpdateInputGroup.tsx
  src/pages/update/VUpdateRegisterForm.tsx
Labels: Request Review
